version: '3.8'
services:
  db:
    image: postgres:15
    container_name: antisnow-db-1
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: antisnow_db
    volumes:
      - antisnow_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: antisnow-backend-1
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/backend/uploads # ПУТЬ К ФОТО
    environment:
      DATABASE_URL: postgresql://user_admin:password@db:5432/antisnow_db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: antisnow-nginx-1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  antisnow_postgres_data: