server {
    listen 80;
    server_name 37.230.169.95;

    # Фронтенд (просто файлы)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Бэкенд (перенаправление на Python)
    # Важно: слеш в конце proxy_pass убирает /api/ при передаче в FastAPI
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Статика (фотографии)
    location /api/static_uploads/ {
        proxy_pass http://backend:8000/static_uploads/;
    }
}